tap "derailed/k9s"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"
brew "python@3.9"
brew "glib"
brew "awscli"
brew "bash-completion"
brew "guile"
brew "unbound"
brew "gnutls"
brew "emacs", restart_service: :changed
brew "git"
brew "git-extras"
brew "gnupg"
brew "gobject-introspection"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "graphviz"
brew "helm"
brew "jmeter"
brew "kubernetes-cli", link: false
brew "leptonica"
brew "libass"
brew "libbluray"
brew "magic-wormhole"
brew "mas"
brew "maven-completion"
brew "mkcert"
brew "nghttp2"
brew "node"
brew "socat"
brew "openshift-cli"
brew "python@3.10", link: false
brew "pre-commit"
brew "python@3.8", link: false
brew "sops"
brew "srt"
brew "watch"
brew "wget"
brew "yarn"
cask "aerial"
cask "applepi-baker"
cask "cakebrew"
cask "cool-retro-term"
cask "diffmerge"
cask "docker"
cask "drawio"
cask "dropbox"
cask "firefox"
cask "fork"
cask "gas-mask"
cask "intellij-idea"
cask "iterm2"
cask "jdk-mission-control"
cask "jetbrains-toolbox"
cask "keepassxc"
cask "maccy"
cask "macdown"
cask "microsoft-teams"
cask "obsidian"
cask "postman"
cask "processing"
cask "psequel"
cask "rocket-chat"
cask "sourcetrail"
cask "sourcetree"
cask "spotify"
cask "stats"
cask "visual-studio-code"
cask "visual-studio-code@insiders"
cask "visualvm"
cask "whatsapp"
mas "AdGuard for Safari", id: 1440147259
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
vscode "asciidoctor.asciidoctor-vscode"
vscode "cstuder.gitlab-ci-validator"
vscode "gitlab.gitlab-workflow"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-vscode-remote.remote-containers"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "waderyan.gitblame"
vscode "yzhang.markdown-all-in-one"
