tap "derailed/k9s"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "python@3.9"
brew "glib"
brew "awscli"
brew "bash-completion"
brew "guile"
brew "unbound"
brew "gnutls"
brew "emacs", restart_service: true
brew "git"
brew "git-extras"
brew "gnupg"
brew "gobject-introspection"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "graphviz"
brew "helm"
brew "jmeter"
brew "kubernetes-cli", link: false
brew "leptonica"
brew "libass"
brew "libbluray"
brew "magic-wormhole"
brew "mas"
brew "maven-completion"
brew "mkcert"
brew "nghttp2"
brew "node"
brew "socat"
brew "openshift-cli"
brew "python@3.10"
brew "pre-commit"
brew "python@3.8"
brew "sops"
brew "srt"
brew "watch"
brew "wget"
brew "yarn"
cask "adobe-acrobat-reader"
cask "aerial"
cask "applepi-baker"
cask "cakebrew"
cask "cool-retro-term"
cask "diffmerge"
cask "docker"
cask "drawio"
cask "dropbox"
cask "firefox"
cask "fork"
cask "gas-mask"
cask "intellij-idea"
cask "iterm2"
cask "jdk-mission-control"
cask "jetbrains-toolbox"
cask "keepassxc"
cask "maccy"
cask "macdown"
cask "microsoft-teams"
cask "obsidian"
cask "postman"
cask "processing"
cask "psequel"
cask "rocket-chat"
cask "sourcetrail"
cask "sourcetree"
cask "spotify"
cask "stats"
cask "visual-studio-code"
cask "visual-studio-code-insiders"
cask "visualvm"
cask "whatsapp"
mas "AdBlock Pro", id: 1018301773
mas "Cloud Battery", id: 1481005137
mas "feedly", id: 865500966
mas "Jolt of Caffeine", id: 1437130425
mas "Keynote", id: 409183694
mas "Monit", id: 1014850245
mas "Numbers", id: 409203825
mas "Pocket", id: 568494494
mas "Polyglot", id: 1471801525
mas "Trello", id: 1278508951
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
